name: psquad-asset-process-infra
description: Protocol Squad Asset Process Infra
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
