name: Deploy Pulumi Script to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.QUEUES_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.QUEUES_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Set up Pulumi CLI
    - name: Install Pulumi
      uses: pulumi/actions@v4

    # Install dependencies
    - name: Install dependencies
      working-directory: infra
      run: npm install

    # Run Pulumi deployment
    - name: Deploy using Pulumi
      working-directory: infra
      run: |
        pulumi stack init prod
        pulumi config set deployToLocalstack false --stack prod
        pulumi up --yes
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}